export default {
  login: "missdobis",
  id: 60183363,
  node_id: "MDQ6VXNlcjYwMTgzMzYz",
  avatar_url: "https://avatars1.githubusercontent.com/u/60183363?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/missdobis",
  html_url: "https://github.com/missdobis",
  followers_url: "https://api.github.com/users/missdobis/followers",
  following_url:
    "https://api.github.com/users/missdobis/following{/other_user}",
  gists_url: "https://api.github.com/users/missdobis/gists{/gist_id}",
  starred_url: "https://api.github.com/users/missdobis/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/missdobis/subscriptions",
  organizations_url: "https://api.github.com/users/missdobis/orgs",
  repos_url: "https://api.github.com/users/missdobis/repos",
  events_url: "https://api.github.com/users/missdobis/events{/privacy}",
  received_events_url: "https://api.github.com/users/missdobis/received_events",
  type: "User",
  site_admin: false,
  name: "missdobis",
  company: "DevCareers",
  blog: "",
  location: "Planet Jupiter",
  email: "missdobis@gmail.com",
  hireable: null,
  bio: null,
  twitter_username: "missdobis",
  public_repos: 17,
  public_gists: 10,
  followers: 2,
  following: 2,
  created_at: "2020-01-22T13:27:04Z",
  updated_at: "2020-10-28T18:19:53Z",
};
